### ISSUE TITLE
source of the hdf5 data

### ISSUE THREAD

**Issue by adeze** [vaexio/streamlit-600million-gdelt-news-articles#1]
Did you build your own dataset from combing and processing the 15minute event.gz tsv files into the hdf5 file that is referenced,or;
is that an export from bigquery ? 
and;
what was the method you found that worked best to build that hdf5 file?

**Comment by JovanVeljanoski** [comment]
Hi, 

For the version of the data used for this dashboard, i used the dataset from bigquery via `vaex.contribute.io.big`.

When I first discovered this dataset (few years ago), downloaded the individual csv files converted them to hdf5, and then joined them together with vaex. 

Getting the data from bigquery is easier now (but you need to pay), and downloading and converting the individual csv files is "free"  but will const you time to convert everything, and you will end up with multiple copies of the data so make sure you have enough space.

**Comment by adeze** [comment]
ok. yes I understand- I used to use the zip files initially too then bq.
